name: Update issues based on board

on:
  project_card:
    types:
      - moved

jobs:
  moved_backlog:
    if: github.event.project_card.column_id == '16074546'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: update labels
        uses: andymckay/labeler@master
        with:
          add-labels: "FP: Planned"
          remove-labels: "FP: Completed, FP: In Development, FP: Unplanned"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  moved_inprogress_rft_testing:
    if: |
      github.event.project_card.column_id == '16074551' ||
      github.event.project_card.column_id == '16074554' ||
      github.event.project_card.column_id == '16074555'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: update labels
        uses: andymckay/labeler@master
        with:
          add-labels: "FP: In Development"
          remove-labels: "FP: Unplanned, FP: Planned, FP: Completed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  moved_done:
    if: github.event.project_card.column_id == '16074560'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: update labels
        uses: andymckay/labeler@master
        with:
          add-labels: "FP: Completed"
          remove-labels: "FP: Unplanned, FP: Planned, FP: In Development"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  moved_parkinglot:
    if: github.event.project_card.column_id == '16074567'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: update labels
        uses: andymckay/labeler@master
        with:
          add-labels: "FP: Unplanned"
          remove-labels: "FP: Completed, FP: Planned, FP: In Development"
          repo-token: ${{ secrets.GITHUB_TOKEN }}